#!/usr/bin/env bash
# Generates a build_info.txt file containing version, commit, date, and
# branch information. Called by the GitHub Actions workflow.
#
# Usage: ./scripts/generate_build_info.sh <version> <commit_sha> <branch> <run_number>
#
# Outputs: build_info.txt in the current directory.

set -euo pipefail

VERSION="${1:-unknown}"
COMMIT_SHA="${2:-unknown}"
BRANCH="${3:-unknown}"
RUN_NUMBER="${4:-0}"
BUILD_DATE="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
COMMIT_SHORT="${COMMIT_SHA:0:7}"

cat > build_info.txt << EOF
============================================================
  Location MK — Build Information
============================================================

Version:       ${VERSION}
Build Number:  ${RUN_NUMBER}
Commit:        ${COMMIT_SHORT} (${COMMIT_SHA})
Branch:        ${BRANCH}
Build Date:    ${BUILD_DATE}
Build Runner:  GitHub Actions (ubuntu-latest)

------------------------------------------------------------
This file was auto-generated by the CI/CD pipeline.
Do not edit manually.
============================================================
EOF

echo "✅ build_info.txt generated:"
cat build_info.txt
